#!/bin/bash

#	Configure and make wx using the current git branch name
#
#	Neil Mayhew - 2010-04-20

set -e

CONFIGURATION=(
	--enable-unicode --enable-debug
)

revpath()
{
	sed 's#[^/]*#..#g' <<<"$1"
}

git-branch-name()
{
	git describe --contains --all --always ${1:-HEAD}
}

SRC=${1:-../wxWidgets}
BRANCH=$(cd $SRC; git-branch-name)
SRC=$(revpath $BRANCH)/$SRC

rm -rf $BRANCH
mkdir -p $BRANCH
cd $BRANCH

$SRC/configure "${CONFIGURATION[@]}"
make "${@:2}"
make install DESTDIR=$(pwd)/destdir
