#!/bin/bash

#	Configure, make and install wx to /usr/local
#
#	Neil Mayhew - 2010-04-22

set -e

trap '[ $? -eq 0 ] || echo "FAILED!"' 0

revpath()
{
	sed 's#[^/]*#..#g' <<<"$1"
}

wx-version()
{
	sed -n '/wxVERSION_STRING/s/.*"wxWidgets \(.*\)".*/\1/p' "$1/include/wx/version.h"
}

SRC=${1:-.}
VERSION=$(wx-version "$SRC")
BUILD=build-ud-$VERSION
PREFIX=/opt/wx/$VERSION

case "$SRC" in
([^/]*) SRC=$(revpath $BUILD)/$SRC;;
esac
SRC=${SRC%/.}

CONFIGURATION=(
	--enable-unicode --enable-debug --prefix="$PREFIX"
)

rm -rf $BUILD
mkdir -p $BUILD
cd $BUILD

echo
echo "Configuring in $BUILD"
echo "Output redirected to $BUILD/configure.out"

${SRC}/configure "${CONFIGURATION[@]}" &>configure.out

echo
echo "Making in $BUILD"
echo "Output redirected to $BUILD/make.out"

make "${@:2}" &>make.out

echo
echo "Installing from $BUILD"
echo "Output redirected to $BUILD/install.out"

sudo -v -p "Enter password for sudo make install: "
sudo make install &>install.out
