#!/bin/bash

#	Configure and make wx using the current git branch name
#
#	Neil Mayhew - 2010-04-20

set -e

trap '[ $? -eq 0 ] || echo "FAILED!"' 0

revpath()
{
	sed 's#[^/]*#..#g' <<<"$1"
}

git-branch-name()
{
	git describe --contains --all --always ${1:-HEAD}
}

wx-version()
{
	sed -n '/wxVERSION_STRING/s/.*"wxWidgets \(.*\)".*/\1/p' "$1/include/wx/version.h"
}

SRC=${1:-../wxWidgets}
VERSION=$(wx-version "$SRC")
BUILD=$(cd $SRC; git-branch-name)
PREFIX=/opt/wx/$VERSION

case "$SRC" in
([^/]*) SRC=$(revpath $BUILD)/$SRC;;
esac
SRC=${SRC%/.}

CONFIGURATION=(
	--enable-unicode --enable-debug --prefix="$PREFIX"
)
rm -rf $BUILD
mkdir -p $BUILD
cd $BUILD

$SRC/configure "${CONFIGURATION[@]}"
make "${@:2}"
make install DESTDIR=$(pwd)/destdir
