#!/usr/bin/env bash

#	Install a built wx
#
#	Neil Mayhew - 2010-04-20

set -e

git-branch-name()
{
	git describe --contains --all --always ${1:-HEAD}
}

SRC=../wxWidgets
BRANCH=$1

if [ -z "$BRANCH" ]; then
	BRANCH=$(cd $SRC; git-branch-name)
fi

cd "$BRANCH/destdir"
find * ! -type d -print | sudo cpio -pvdmu -R root: /
